export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SIGNUP_SUCCESS = 'REGISTER_SUCCESS';
export const SIGNUP_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const RESTAURANT_LOADED = 'RESTAURANT_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const REGISTERED_EVENTS = 'REGISTERED_EVENTS';
export const SUBMITTED_EVENTS = 'SUBMITTED_EVENTS';
export const REGISTERED_EVENTS_ERROR = 'REGISTERED_EVENTS_ERROR';
export const SUBMITTED_EVENTS_ERROR = 'SUBMITTED_EVENTS_ERROR';
export const GET_IMAGE = 'GET_IMAGE';
export const IMAGE_ERROR = 'IMAGE_ERROR';
export const RES_IMAGE_ERROR = 'RES_IMAGE_ERROR';

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const ADD_DISH_ERROR = 'ADD_DISH_ERROR';
export const GET_MENU = 'GET_MENU';
export const GET_MENU_ERROR = 'GET_MENU_ERROR';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const GET_ORDERS_ALL = 'GET_ORDERS_ALL';
export const GET_ORDERS_ALL_ERROR = 'GET_ORDERS_ALL_ERROR';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_ERROR = 'UPDATE_STATUS_ERROR';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR';

export const CUSTOMER_ORDERS = 'CUSTOMER_ORDERS';
export const CUSTOMER_ORDERS_ERROR = 'CUSTOMER_ORDERS_ERROR';

export const CREATE_EVENT = 'CREATE_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';
export const EVENT_REGISTER_SUCCESS = 'EVENT_REGISTER_SUCCESS';
export const EVENT_REGISTER_ERROR = 'EVENT_REGISTER_ERROR';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const LIST_ERROR = 'LIST_ERROR';
export const CLEAR_EVENT = 'CLEAR_EVENT';

export const ALL_RESTAURANTS = 'ALL_RESTAURANTS';
export const ALL_RESTAURANTS_ERROR = 'ALL_RESTAURANTS_ERROR';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const RESTAURANT_ERROR = 'RESTAURANT_ERROR';
export const PLACEORDER = 'PLACEORDER';
export const PLACEORDER_ERROR = 'PLACEORDER_ERROR';
export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';
export const GET_RES_MENU = 'GET_RES_MENU';
export const GET_RES_MENU_ERROR = 'GET_RES_MENU_ERROR';

export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';
export const SEARCH_RESTAURANTS_ERROR = 'SEARCH_RESTAURANTS_ERROR';
export const RESULTS = 'RESULTS';
export const RESULTS_ERROR = 'RESULTS_ERROR';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const GET_CUSTOMER = 'GET_CUSTOMER';
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR';
export const GET_CUSTOMER_REVIEW = 'GET_CUSTOMER_REVIEW';
export const CUSTOMER_REVIEW_ERROR = 'CUSTOMER_REVIEW_ERROR';
